config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :announcements
  resources :equiplists
  get 'equips/index'
  get 'equips/show'
  get 'equips/new'
  get 'equips/create'
  get 'equips/destroy'
  post 'mainportal/adminModelEquip'
  post 'mainportal/adminModelUsers'
  root 'mainpage#landing'
  post 'mainportal/chairmanStats'
  post 'mainportal/chairmanStatsPayment'
  post 'mainportal/chairmanStatsSamples'
  post 'mainportal/adminAllSlots'




  resources :ft_nms
  resources :ansies
  resources :equipment_tables
  resources :lasers
  resources :three_d_scanners
  resources :impedance_analies
  resources :high_temp_vaccums
  resources :liquid_nitrogens
  resources :gas_sensings
  resources :ultra_centrifuges
  resources :probe_sonicators
  resources :glove_boxes
  resources :milli_qs
  resources :electro_chemicals
  resources :five_axis
  resources :micro_edms
  resources :spark_os
  resources :spectro_radio_meters
  resources :gaits
   resources :grindings
   resources :friction_stirs
   resources :frictions
   resources :multi_impact_testers
   resources :ball_mailings
   resources :glows
   resources :tribometers
   resources :low_fatigues
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   default_url_options :host => "localhost:3000"
    resources :zeta_potential_sizes
    resources :scratch_indentations
    resources :integrated_multi_role_testers
    resources :ion_chromotographies
    resources :advance_molecular_rheometers
    resources :icp_ms
    resources :ft_nmrs
    resources :atomic_force_microscopes
    resources :cell_imagings
    resources :uv_vis_nirs
    resources :hrlcms
    resources :bets
    resources :tga_fttrs
    resources :raman_microscopes
    resources :three_d_non_contacts
    resources :hr_fesem_js
    resources :hr_fesem_cs
    resources :xrds
    resources :faculties, controller: 'faculties'

    devise_for :users

    post 'home/developer'
    get 'mainportal/admindashboard'
    get 'mainportal/adminAllSlots'
    get 'mainportal/adminModelUsers'
    get 'mainportal/adminModelEquip'
    get 'mainportal/adminExpress'
    get 'mainportal/adminExpSlot'
    get 'mainportal/adminModelEquipWeeks'
    get 'mainportal/adminModelPayment'
    get 'mainportal/adminStats'
    get 'mainportal/chairmanDashboard'
    get 'mainportal/chairmanStats'
    get 'mainportal/chairmanEquip'
    get 'mainportal/chairmanPayment'
    get 'mainportal/chairmanUsers'
    get 'mainportal/chairmanStatsPayment'
    get 'mainportal/chairmanStatsSamples'
    get 'mainportal/exportfile'
    post 'download_liquid_nitrogen', to: 'mainportal#download_liquid_nitrogen', format: :csv
    get 'mainpage/landing'
    get 'home/index'
    get 'home/myslots'
    get 'home/anish'
    get 'know/xrd'
    get 'records/record'

    get 'home/mainPage'
    get 'mainpage/people'
    get 'mainpage/user_type'
    get 'mainpage/about_us'
    get 'mainpage/gallery'
    get 'mainpage/facility'
    get 'mainpage/announcement_admin'

    get 'mainpage/micromachining'
    get 'mainpage/xrd'
    get 'mainpage/axes_5'
    get 'mainpage/metal_3D'
    get 'mainpage/friction_stir'
    get 'mainpage/hvaf_hvof'
    get 'mainpage/hollow_fibre'

    get 'mainpage/fesem_c'
    get 'mainpage/hr_fesem_jeol'
    get 'mainpage/hr_lcms'
    get 'mainpage/xrd'
    get 'mainpage/three'
    get 'mainpage/bet'
    get 'mainpage/uv_vis'
    get 'mainpage/rheometer'
    get 'mainpage/raman'
    get 'mainpage/scanner_3d'
    get 'mainpage/tribometer'
    get 'mainpage/icp_ms'
    get 'mainpage/gas_sensing'
    get 'mainpage/atomic'
    get 'mainpage/tga'
    get 'mainpage/cell_imaging'
    get 'mainpage/ft_nmr'
    get 'mainpage/spark_oes'
    get 'mainpage/scratch_indentation'
    get 'mainpage/glow_discharge'
    get 'mainpage/multi_impact_test'
    get 'mainpage/integ_multirole'
    get 'mainpage/zeta'
    get 'mainpage/pressure_plate'
    get 'mainpage/impedance'
    get 'mainpage/laser'
    get 'mainpage/ion_chromatography'
    get 'mainpage/spectro'
    get 'mainpage/low_force_fatigue'
    get 'mainpage/chemisorption'
    get 'mainpage/instrumented_impact'
    get 'mainpage/gas_chromatography'
    get 'mainpage/proton_transfer'
    get 'mainpage/servo_hydraulic'
    get 'mainpage/gait'

    get 'mainpage/auto_multi_speci_polish'
    get 'mainpage/electro_chem'
    get 'mainpage/ultra_centrifuge'
    get 'mainpage/milli_q'
    get 'mainpage/glove_box'
    get 'mainpage/probe_sonicator'
    get 'mainpage/uv_ozone'
    get 'mainpage/high_temp_vac'
    get 'mainpage/liq_nitrogen'
    get 'mainpage/ball_milling'

    get 'mainpage/instrument_list'
    get 'mainpage/ft_nmr'
    get 'mainpage/xrd'
    get 'mainpage/hr_fesem_carl'
    get 'mainpage/friction_wear'
    get 'mainpage/multi_impact_test'
    get 'mainpage/multirole_mech'

    get 'feedbacks/index'


   get 'slot_mailer/xrd'
   get 'slot_mailer/advance_molecular_rheometer'
   get 'slot_mailer/bet'
   get 'slot_mailer/ball_mailing'
   get 'slot_mailer/cell_imaging'
   get 'slot_mailer/electro_chemical'
   get 'slot_mailer/five_axi'
   get 'slot_mailer/friction'
   get 'slot_mailer/ftnmr'
   get 'slot_mailer/gait'
   get 'slot_mailer/gas_sensing'
   get 'slot_mailer/glove_box'
   get 'slot_mailer/glow'
   get 'slot_mailer/grinding'
   get 'slot_mailer/high_temp_vaccum'
   get 'slot_mailer/hr_fesem_c'
   get 'slot_mailer/hr_fesem_j'
   get 'slot_mailer/icp_m'
   get 'slot_mailer/hr_lcm'
   get 'slot_mailer/impedence_analyzer'
   get 'slot_mailer/integrated_multi_role_tester'
   get 'slot_mailer/ion_chromatography'
   get 'slot_mailer/liquid_nitrogen'
   get 'slot_mailer/low_fatigue'
   get 'slot_mailer/laser'
   get 'slot_mailer/micro_edm'
   get 'slot_mailer/milli_q'
   get 'slot_mailer/multi_impact_tester'
   get 'slot_mailer/probe_sonicator'
   get 'slot_mailer/raman_microscope'
   get 'slot_mailer/scratch_indentation'
   get 'slot_mailer/spark_o'
   get 'slot_mailer/spectro_radio_meter'
   get 'slot_mailer/tga_fttr'
   get 'slot_mailer/three_d_non_contact'
   get 'slot_mailer/three_d_scanner'
   get 'slot_mailer/tribometer'
   get 'slot_mailer/ultra_centrifuge'
   get 'slot_mailer/uv_vis_nir'
   get 'slot_mailer/zeta_potential_size'




















    get 'home/developer'
    get 'slotbooker/xrd'
    get 'slotbooker/xrd1'
    post 'slotbooker/xrd1'
    patch 'slotbooker/xrd1'
    get 'slotbooker/xrd2'
    get 'slotbooker/xrd3'
    get 'slotbooker/xrd4'
    get 'slotbooker/atomic'
    get 'slotbooker/atomic1'
    get 'slotbooker/atomic2'
    get 'slotbooker/atomic3'
    get 'slotbooker/atomic4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/cell'
    get 'slotbooker/cell1'
    get 'slotbooker/cell2'
    get 'slotbooker/cell3'
    get 'slotbooker/cell4'
    get 'slotbooker/fesemc'
    get 'slotbooker/fesemc1'
    get 'slotbooker/fesemc2'
    get 'slotbooker/fesemc3'
    get 'slotbooker/fesemc4'
    get 'slotbooker/fesemj'
    get 'slotbooker/fesemj1'
    get 'slotbooker/fesemj2'
    get 'slotbooker/fesemj3'
    get 'slotbooker/fesemj4'
    get 'slotbooker/icp'
    get 'slotbooker/icp1'
    get 'slotbooker/icp2'
    get 'slotbooker/icp3'
    get 'slotbooker/icp4'
    get 'slotbooker/laser'
    get 'slotbooker/laser1'
    get 'slotbooker/laser2'
    get 'slotbooker/laser3'
    get 'slotbooker/laser4'
    get 'slotbooker/lcms'
    get 'slotbooker/lcms1'
    get 'slotbooker/lcms2'
    get 'slotbooker/lcms3'
    get 'slotbooker/lcms4'
    get 'slotbooker/raman'
    get 'slotbooker/raman1'
    get 'slotbooker/raman2'
    get 'slotbooker/raman3'
    get 'slotbooker/raman4'
    get 'slotbooker/tga'
    get 'slotbooker/tga1'
    get 'slotbooker/tga2'
    get 'slotbooker/tga3'
    get 'slotbooker/tga4'
    get 'slotbooker/threednon'
    get 'slotbooker/threednon1'
    get 'slotbooker/threednon2'
    get 'slotbooker/threednon3'
    get 'slotbooker/threednon4'
    get 'slotbooker/uv'
    get 'slotbooker/uv1'
    get 'slotbooker/uv2'
    get 'slotbooker/uv3'
    get 'slotbooker/uv4'
    get 'slotbooker/spectro'
    get 'slotbooker/spectro1'
    get 'slotbooker/spectro2'
    get 'slotbooker/spectro3'
    get 'slotbooker/spectro4'
    get 'slotbooker/spark'
    get 'slotbooker/spark1'
    get 'slotbooker/spark2'
    get 'slotbooker/spark3'
    get 'slotbooker/spark4'
    get 'slotbooker/fiveaxis'
    get 'slotbooker/fiveaxis1'
    get 'slotbooker/fiveaxis2'
    get 'slotbooker/fiveaxis3'
    get 'slotbooker/fiveaxis4'
    get 'slotbooker/elctro'
    get 'slotbooker/elctro1'
    get 'slotbooker/elctro2'
    get 'slotbooker/elctro3'
    get 'slotbooker/elctro4'
    get 'slotbooker/nitrogen'
    get 'slotbooker/gassensing'
    get 'slotbooker/gassensing1'
    get 'slotbooker/gassensing2'
    get 'slotbooker/gassensing3'
    get 'slotbooker/gassensing4'
    get 'slotbooker/centrifuge'
    get 'slotbooker/centrifuge1'
    get 'slotbooker/centrifuge2'
    get 'slotbooker/centrifuge3'
    get 'slotbooker/centrifuge4'
    get 'slotbooker/probe'
    get 'slotbooker/probe1'
    get 'slotbooker/probe2'
    get 'slotbooker/probe3'
    get 'slotbooker/probe4'
    get 'slotbooker/glove'
    get 'slotbooker/glove1'
    get 'slotbooker/glove2'
    get 'slotbooker/glove3'
    get 'slotbooker/glove4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/milli'
    get 'slotbooker/integrated'
    get 'slotbooker/integrated1'
    get 'slotbooker/integrated2'
    get 'slotbooker/integrated3'
    get 'slotbooker/integrated4'
    get 'slotbooker/scratch'
    get 'slotbooker/scratch1'
    get 'slotbooker/scratch2'
    get 'slotbooker/scratch3'
    get 'slotbooker/scratch4'
    get 'slotbooker/threescanner'
    get 'slotbooker/threescanner1'
    get 'slotbooker/threescanner2'
    get 'slotbooker/threescanner3'
    get 'slotbooker/threescanner4'
    get 'slotbooker/impdeance'
    get 'slotbooker/impdeance1'

app/models/friction.rb
class Friction < ApplicationRecord
  has_many_attached :references
  belongs_to :user
  has_one :equipment_table, :dependent => :destroy
  accepts_nested_attributes_for :equipment_table
  serialize :material
  after_create :update_equipment
  def update_equipment
    equipment_table = self.equipment_table # Find the specific AnotherTable record
    equipment_table.update(app_no: "CRF/FRN/#{self.id}") 
  end
end

app/controllers/frictions_controller.rb
class FrictionsController < ApplicationController
  before_action :set_friction, only: %i[ show edit update destroy ]

  # GET /frictions or /frictions.json
  def index
    @frictions = Friction.all
  end

  # GET /frictions/1 or /frictions/1.json
  def show
  end

  # GET /frictions/new
  def new
    @friction = Friction.new
    @user=User.find(params[:id])
    @friction.build_equipment_table
    @slot_type = params[:slot_type]
    @equiplist = Equiplist.all
    @equiplist_expressslot = Equiplist.where(name: "Friction Stir Welding/Surfacing(FSW)").pluck(:expressslot).map { |slot| slot.nil? ? "nil" : slot.to_i }
    @equiplist_expressstart = Equiplist.where(name: "Friction Stir Welding/Surfacing(FSW)").pluck(:expressstart).first&.strftime("%d/%m/%Y")
    @equiplist_expressend = Equiplist.where(name: "Friction Stir Welding/Surfacing(FSW)").pluck(:expressend).first&.strftime("%d/%m/%Y")

  end

  # GET /frictions/1/edit
  def edit
  end

  # POST /frictions or /frictions.json
  def create
    @friction = Friction.new(friction_params)
    @friction.user=current_user
    @friction.status="pending"
    @friction.build_equipment_table
    if(@friction.entry_type== "manual")
      @friction.equipment_table.dummy = "proforma_confirmed"
      @friction.equipment_table.equipname = @friction.dummy1
      @friction.equipment_table.pay = @friction.amount
      @friction.equipment_table.username = @friction.dummy2
      @friction.equipment_table.debit_head = @Friction.debit
      @friction.equipment_table.role = @friction.dummy3
      @friction.dummy2 = nil
      @friction.dummy3 = nil
    else
    @friction.equipment_table.dummy = "alloted"
    @friction.equipment_table.username = @friction.user.name
    @friction.equipment_table.equipname = "Friction Stir Welding/Surfacing(FSW)"
    @friction.equipment_table.debit_head = @friction.debit
    @friction.equipment_table.role = @friction.user.role
    @friction.equipment_table.email = @friction.user.email
    @friction.equipment_table.dept = @friction.user.department
    @friction.equipment_table.profesion = @friction.user.profession
    @friction.equipment_table.orgname = @friction.user.orgname
  end
  @equiplist = Equiplist.all
  @equiplist_expressslot = Equiplist.where(name: "Friction Stir Welding/Surfacing(FSW)").pluck(:expressslot).map { |slot| slot.nil? ? "nil" : slot.to_i }

    respond_to do |format|
      if @friction.save
        if  @friction.expresssample.present?
         equiplist = Equiplist.where(name: "Friction Stir Welding/Surfacing(FSW)").first
         equiplist.expressslot =equiplist.expressslot- @friction.expresssample
         equiplist.save
        end
        if @friction.user.role=='student'||@friction.user.role=='faculty'
          FrictionMailer.with(id:@friction.id, userid:current_user.id).InternalMail.deliver_later
        else
          FrictionMailer.with(id:@friction.id, userid:current_user.id).ExternalMail.deliver_later
        end
        if @friction.entry_type=="manual"
            format.html { redirect_to payment_paymentM_path, notice: "friction was successfully created." }
            format.json { render :show, status: :created, location: @friction }
        else
        format.html { redirect_to home_index_path, notice: "Friction was successfully created." }
        format.json { render :show, status: :created, location: @friction }
      end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frictions/1 or /frictions/1.json
  def update
      @friction.status="alloted"
      @friction.build_equipment_table
    respond_to do |format|
      if @friction.update(friction_params)
        if @friction.status!= 'completed'
          FrictionAllotedMailer.with(id:@friction.id, userid:current_user.id).Mail.deliver_later
        end
        format.html { redirect_to slotbooker_fric_path(@friction), notice: "Friction was successfully updated." }
        format.json { render :show, status: :ok, location: @friction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frictions/1 or /frictions/1.json
  def destroy
    @friction.destroy

    respond_to do |format|
      format.html { redirect_to frictions_url, notice: "Friction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friction
      @friction = Friction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friction_params
      params.require(:friction).permit(:sample, :material, :pstype, :tool, :toolnom, :rspeed, :wspeed, :otforce, :wtemp,:temp, :measurement, :depth, :ptforce, :more, :status, :slotdate, :slottime, :debit,:user_id,:entry_type, :amount, :dummy1,:dummy2,:dummy3,:slottype,:expresssample,equipment_table_attributes: [:username, :app_no, :debit_head, :dummy, :pay, :dept, :equipname, :email,:role, :profesion, :orgaddress, :orgname] ,material: [], references: [])
    end
end

app/helpers/frictions_helper.rb
module FrictionsHelper
end

app/views/frictions/_form.html.erb
<%= stylesheet_link_tag "loginFeatures"%>
<%= stylesheet_link_tag "equipmentQuestion"%>




<%=render "partials/loginHeading"%>
<%=render "partials/formsBackbtn"%>



<div class="container">
    <div id="equipment-name">
      <h1>Friction Stir Welding/Surfacing(FSW)</h1>
    </div>
    <div class='hero'>
      <%= form_with(model: friction) do |form| %>
        <% if friction.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(friction.errors.count, "error") %> prohibited this friction from being saved:</h2>

            <ul>
              <% friction.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

    <p class="text-warning">Max. Sample size 150 x 150 mm; Thickness 6 mm</p>
    <% if @slot_type=="regular"%>
    <div class="input-group mb-3">
      <%= form.label :sample,"No of Samples", class:"input-group-text", for:"sample-no"%>
      <%= form.select(:sample, [1, 2,3,4,5,6,7,8,9,10], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "sample-no",:required => true}) %>
    </div>
   <%else%>
   <div id="instruct">
       <span class="input-group-text text-danger" id="basic-addon1">Express slot is available from <%=@equiplist_expressstart%> to <%=@equiplist_expressend%></span>
       <p class="text-danger"></p>
   </div>
   <div class="input-group mb-3">
     <%= form.label :expresssample,"No of Samples Express", class:"input-group-text", for:"xrd-select-no-of-equipment"%>
     <%= form.select :expresssample, options_for_select(1..@equiplist_expressslot[0]), prompt: "No. of available samples", class:"form-select" %>
   </div>
   <%end%>

    <div>
        <p class="fw-bold">Sample Material</p>
        <% options = ['Aluiminium', 'Copper','Metal matrix composition'] %>
        <% options.each do |option| %>
          <%= check_box_tag 'friction[material][]', option, @friction.material.include?(option) %>
          <%= label_tag "friction_material_#{option}", option %><br>
        <% end %>

    </div>

    <div class="input-group mb-3">
      <%= form.label :pstype,"Type of process", class:"input-group-text", for:"process-type"%>
      <%= form.select(:pstype, ["Welding","Surface Processing"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "process-type",:required => true}) %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :tool,"Tool required", class:"input-group-text", for:"tool-reqd"%>
      <%= form.select(:tool, ["Yes","No"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "tool-reqd",:required => true}) %>
    </div>

    <div class="input-group mb-3 vis" id="mention_tool_div">
      <%= form.text_field :toolnom, class:"form-control", id:"tool-nomenclature", placeholder:"Tool Nomenclature" %>
    </div>

    <div class="process-param">
        <p class="text-success fw-bold">Process Parameter</p>

        <div class="input-group mb-3">
          <%= form.label :rspeed, "Rotational Speed", class:"input-group-text",for:"rotation-speed"%>
          <%= form.text_field :rspeed, class:"form-control", id:"rotation-speed", placeholder:""%>
          <%= form.label :rspeed, "Rpm", class:"input-group-text",for:"rotation-speed"%>
        </div>

        <div class="input-group mb-3">
          <%= form.label :wspeed, "Welding Speed", class:"input-group-text",for:"weld-speed"%>
          <%= form.text_field :wspeed, class:"form-control", id:"weld-speed", placeholder:""%>
          <%= form.label :wspeed, "mm/min", class:"input-group-text",for:"weld-speed"%>
        </div>
    </div>

    <div class="process-param">
        <p class="text-success fw-bold">Optional Parameter</p>

        <div class="input-group mb-3">
          <%= form.label :otforce, "Thrust Force", class:"input-group-text",for:"thrust-force"%>
          <%= form.text_field :otforce, class:"form-control", id:"thrust-force", placeholder:""%>
          <%= form.label :otforce, "kN", class:"input-group-text",for:"thrust-force"%>
        </div>

        <div class="input-group mb-3">
          <%= form.label :temp,"Welding Temp (IR type)", class:"input-group-text", for:"weld-temp"%>
          <%= form.select(:temp, ["Yes","No"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "weld-temp",:required => true}) %>
        </div>

        <div class="input-group mb-3">
          <%= form.label :measurement,"Acoustic Measurement", class:"input-group-text", for:"acoustic-measure"%>
          <%= form.select(:measurement, ["Yes","No"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "acoustic-measure",:required => true}) %>
        </div>

    </div>

    <div class="process-param">
        <p class="text-success fw-bold">Penetration Parameter</p>

        <div class="input-group mb-3">
          <%= form.label :depth, "Depth", class:"input-group-text",for:"depth"%>
          <%= form.text_field :depth, class:"form-control", id:"depth", placeholder:""%>
          <%= form.label :depth, "mm", class:"input-group-text",for:"depth"%>
        </div>

        <div class="input-group mb-3">
          <%= form.label :ptforce, "Thrust Force", class:"input-group-text",for:"thrust-force-penetrate"%>
          <%= form.text_field :ptforce, class:"form-control", id:"thrust-force-penetrate", placeholder:""%>
          <%= form.label :ptforce, "kN", class:"input-group-text",for:"thrust-force-penetrate"%>
        </div>
    </div>

        <div class="input-group mb-3" id="ref-file">
            <%= form.label :references ,"Attach Reference Paper(optional)" ,for:"upload-file", class:"input-group-text "%>
            <%= form.file_field :references,class:"form-control ",  id:"upload-file",multiple:true  %>
        </div>


          <div class="input-group mb-3">
            <%= form.label :debit,"Choose Debit Head ", class:"input-group-text", for:"debit-head-select" %>
            <%= form.select(:debit, ['Department Operating Cost', 'Student Contingency','CPDA Fund','Project Fund'], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "debit-head-select",:required => true}) %>
        </div>

        <div id="instruct">
            <p class="text-danger">*Please select your Debit head as per your mode of Payment</p>
        </div>


        <div class="mb-3">
          <%= form.label :more,"Additonal information,if any:", class:"input-group-text", for:"tell-us-more" %>
          <%= form.text_area :more, class:"form-control", id:"tell-us-more", rows:"3"%>
        </div>


        <div class="actions">
            <%= form.submit "Submit", class:"btn btn-primary", id:"sbt" %>
        </div>

  </div>
</div>
<%=render "partials/footer" %>

<% end %>


<script>
    let tool = document.getElementById('tool-reqd');
    let mention_tool_div = document.getElementById('mention_tool_div');

    tool.addEventListener('change', () => {
        mention_tool_div.classList.add('vis');


        if (tool.value == 'Yes') {
            mention_tool_div.classList.toggle('vis');
        }

    })
</script>

app/views/frictions/edit.html.erb
<h1>Editing Friction</h1>

<%= render 'form', friction: @friction %>

<%= link_to 'Show', @friction %> |
<%= link_to 'Back', frictions_path %>

app/views/frictions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Frictions</h1>

<table>
  <thead>
    <tr>
      <th>Sample</th>
      <th>Material</th>
      <th>Pstype</th>
      <th>Tool</th>
      <th>Toolnom</th>
      <th>Rspeed</th>
      <th>Wspeed</th>
      <th>Otforce</th>
      <th>Wtemp</th>
      <th>Measurement</th>
      <th>Depth</th>
      <th>Ptforce</th>
      <th>More</th>
      <th>Status</th>
      <th>Slotdate</th>
      <th>Slottime</th>
      <th>Debit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frictions.each do |friction| %>
      <tr>
        <td><%= friction.sample %></td>
        <td><%= friction.material %></td>
        <td><%= friction.pstype %></td>
        <td><%= friction.tool %></td>
        <td><%= friction.toolnom %></td>
        <td><%= friction.rspeed %></td>
        <td><%= friction.wspeed %></td>
        <td><%= friction.otforce %></td>
        <td><%= friction.wtemp %></td>
        <td><%= friction.measurement %></td>
        <td><%= friction.depth %></td>
        <td><%= friction.ptforce %></td>
        <td><%= friction.more %></td>
        <td><%= friction.status %></td>
        <td><%= friction.slotdate %></td>
        <td><%= friction.slottime %></td>
        <td><%= friction.debit %></td>
        <td><%= link_to 'Show', friction %></td>
        <td><%= link_to 'Edit', edit_friction_path(friction) %></td>
        <td><%= link_to 'Destroy', friction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friction', new_friction_path %>

app/views/frictions/new.html.erb
<%= render 'form', friction: @friction %>

app/views/frictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sample:</strong>
  <%= @friction.sample %>
</p>

<p>
  <strong>Material:</strong>
  <%= @friction.material %>
</p>

<p>
  <strong>Pstype:</strong>
  <%= @friction.pstype %>
</p>

<p>
  <strong>Tool:</strong>
  <%= @friction.tool %>
</p>

<p>
  <strong>Toolnom:</strong>
  <%= @friction.toolnom %>
</p>

<p>
  <strong>Rspeed:</strong>
  <%= @friction.rspeed %>
</p>

<p>
  <strong>Wspeed:</strong>
  <%= @friction.wspeed %>
</p>

<p>
  <strong>Otforce:</strong>
  <%= @friction.otforce %>
</p>


<p>
  <strong>Measurement:</strong>
  <%= @friction.measurement %>
</p>

<p>
  <strong>Depth:</strong>
  <%= @friction.depth %>
</p>

<p>
  <strong>Ptforce:</strong>
  <%= @friction.ptforce %>
</p>

<p>
  <strong>More:</strong>
  <%= @friction.more %>
</p>

<p>
  <strong>Status:</strong>
  <%= @friction.status %>
</p>

<p>
  <strong>Slotdate:</strong>
  <%= @friction.slotdate %>
</p>

<p>
  <strong>Slottime:</strong>
  <%= @friction.slottime %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @friction.debit %>
</p>

<%= link_to 'Edit', edit_friction_path(@friction) %> |
<%= link_to 'Back', frictions_path %>