config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :announcements
  resources :equiplists
  get 'equips/index'
  get 'equips/show'
  get 'equips/new'
  get 'equips/create'
  get 'equips/destroy'
  post 'mainportal/adminModelEquip'
  post 'mainportal/adminModelUsers'
  root 'mainpage#landing'
  post 'mainportal/chairmanStats'
  post 'mainportal/chairmanStatsPayment'
  post 'mainportal/chairmanStatsSamples'
  post 'mainportal/adminAllSlots'




  resources :ft_nms
  resources :ansies
  resources :equipment_tables
  resources :lasers
  resources :three_d_scanners
  resources :impedance_analies
  resources :high_temp_vaccums
  resources :liquid_nitrogens
  resources :gas_sensings
  resources :ultra_centrifuges
  resources :probe_sonicators
  resources :glove_boxes
  resources :milli_qs
  resources :electro_chemicals
  resources :five_axis
  resources :micro_edms
  resources :spark_os
  resources :spectro_radio_meters
  resources :gaits
   resources :grindings
   resources :friction_stirs
   resources :frictions
   resources :multi_impact_testers
   resources :ball_mailings
   resources :glows
   resources :tribometers
   resources :low_fatigues
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   default_url_options :host => "localhost:3000"
    resources :zeta_potential_sizes
    resources :scratch_indentations
    resources :integrated_multi_role_testers
    resources :ion_chromotographies
    resources :advance_molecular_rheometers
    resources :icp_ms
    resources :ft_nmrs
    resources :atomic_force_microscopes
    resources :cell_imagings
    resources :uv_vis_nirs
    resources :hrlcms
    resources :bets
    resources :tga_fttrs
    resources :raman_microscopes
    resources :three_d_non_contacts
    resources :hr_fesem_js
    resources :hr_fesem_cs
    resources :xrds
    resources :faculties, controller: 'faculties'

    devise_for :users

    post 'home/developer'
    get 'mainportal/admindashboard'
    get 'mainportal/adminAllSlots'
    get 'mainportal/adminModelUsers'
    get 'mainportal/adminModelEquip'
    get 'mainportal/adminExpress'
    get 'mainportal/adminExpSlot'
    get 'mainportal/adminModelEquipWeeks'
    get 'mainportal/adminModelPayment'
    get 'mainportal/adminStats'
    get 'mainportal/chairmanDashboard'
    get 'mainportal/chairmanStats'
    get 'mainportal/chairmanEquip'
    get 'mainportal/chairmanPayment'
    get 'mainportal/chairmanUsers'
    get 'mainportal/chairmanStatsPayment'
    get 'mainportal/chairmanStatsSamples'
    get 'mainportal/exportfile'
    post 'download_liquid_nitrogen', to: 'mainportal#download_liquid_nitrogen', format: :csv
    get 'mainpage/landing'
    get 'home/index'
    get 'home/myslots'
    get 'home/anish'
    get 'know/xrd'
    get 'records/record'

    get 'home/mainPage'
    get 'mainpage/people'
    get 'mainpage/user_type'
    get 'mainpage/about_us'
    get 'mainpage/gallery'
    get 'mainpage/facility'
    get 'mainpage/announcement_admin'

    get 'mainpage/micromachining'
    get 'mainpage/xrd'
    get 'mainpage/axes_5'
    get 'mainpage/metal_3D'
    get 'mainpage/friction_stir'
    get 'mainpage/hvaf_hvof'
    get 'mainpage/hollow_fibre'

    get 'mainpage/fesem_c'
    get 'mainpage/hr_fesem_jeol'
    get 'mainpage/hr_lcms'
    get 'mainpage/xrd'
    get 'mainpage/three'
    get 'mainpage/bet'
    get 'mainpage/uv_vis'
    get 'mainpage/rheometer'
    get 'mainpage/raman'
    get 'mainpage/scanner_3d'
    get 'mainpage/tribometer'
    get 'mainpage/icp_ms'
    get 'mainpage/gas_sensing'
    get 'mainpage/atomic'
    get 'mainpage/tga'
    get 'mainpage/cell_imaging'
    get 'mainpage/ft_nmr'
    get 'mainpage/spark_oes'
    get 'mainpage/scratch_indentation'
    get 'mainpage/glow_discharge'
    get 'mainpage/multi_impact_test'
    get 'mainpage/integ_multirole'
    get 'mainpage/zeta'
    get 'mainpage/pressure_plate'
    get 'mainpage/impedance'
    get 'mainpage/laser'
    get 'mainpage/ion_chromatography'
    get 'mainpage/spectro'
    get 'mainpage/low_force_fatigue'
    get 'mainpage/chemisorption'
    get 'mainpage/instrumented_impact'
    get 'mainpage/gas_chromatography'
    get 'mainpage/proton_transfer'
    get 'mainpage/servo_hydraulic'
    get 'mainpage/gait'

    get 'mainpage/auto_multi_speci_polish'
    get 'mainpage/electro_chem'
    get 'mainpage/ultra_centrifuge'
    get 'mainpage/milli_q'
    get 'mainpage/glove_box'
    get 'mainpage/probe_sonicator'
    get 'mainpage/uv_ozone'
    get 'mainpage/high_temp_vac'
    get 'mainpage/liq_nitrogen'
    get 'mainpage/ball_milling'

    get 'mainpage/instrument_list'
    get 'mainpage/ft_nmr'
    get 'mainpage/xrd'
    get 'mainpage/hr_fesem_carl'
    get 'mainpage/friction_wear'
    get 'mainpage/multi_impact_test'
    get 'mainpage/multirole_mech'

    get 'feedbacks/index'


   get 'slot_mailer/xrd'
   get 'slot_mailer/advance_molecular_rheometer'
   get 'slot_mailer/bet'
   get 'slot_mailer/ball_mailing'
   get 'slot_mailer/cell_imaging'
   get 'slot_mailer/electro_chemical'
   get 'slot_mailer/five_axi'
   get 'slot_mailer/friction'
   get 'slot_mailer/ftnmr'
   get 'slot_mailer/gait'
   get 'slot_mailer/gas_sensing'
   get 'slot_mailer/glove_box'
   get 'slot_mailer/glow'
   get 'slot_mailer/grinding'
   get 'slot_mailer/high_temp_vaccum'
   get 'slot_mailer/hr_fesem_c'
   get 'slot_mailer/hr_fesem_j'
   get 'slot_mailer/icp_m'
   get 'slot_mailer/hr_lcm'
   get 'slot_mailer/impedence_analyzer'
   get 'slot_mailer/integrated_multi_role_tester'
   get 'slot_mailer/ion_chromatography'
   get 'slot_mailer/liquid_nitrogen'
   get 'slot_mailer/low_fatigue'
   get 'slot_mailer/laser'
   get 'slot_mailer/micro_edm'
   get 'slot_mailer/milli_q'
   get 'slot_mailer/multi_impact_tester'
   get 'slot_mailer/probe_sonicator'
   get 'slot_mailer/raman_microscope'
   get 'slot_mailer/scratch_indentation'
   get 'slot_mailer/spark_o'
   get 'slot_mailer/spectro_radio_meter'
   get 'slot_mailer/tga_fttr'
   get 'slot_mailer/three_d_non_contact'
   get 'slot_mailer/three_d_scanner'
   get 'slot_mailer/tribometer'
   get 'slot_mailer/ultra_centrifuge'
   get 'slot_mailer/uv_vis_nir'
   get 'slot_mailer/zeta_potential_size'




















    get 'home/developer'
    get 'slotbooker/xrd'
    get 'slotbooker/xrd1'
    post 'slotbooker/xrd1'
    patch 'slotbooker/xrd1'
    get 'slotbooker/xrd2'
    get 'slotbooker/xrd3'
    get 'slotbooker/xrd4'
    get 'slotbooker/atomic'
    get 'slotbooker/atomic1'
    get 'slotbooker/atomic2'
    get 'slotbooker/atomic3'
    get 'slotbooker/atomic4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/cell'
    get 'slotbooker/cell1'
    get 'slotbooker/cell2'
    get 'slotbooker/cell3'
    get 'slotbooker/cell4'
    get 'slotbooker/fesemc'
    get 'slotbooker/fesemc1'
    get 'slotbooker/fesemc2'
    get 'slotbooker/fesemc3'
    get 'slotbooker/fesemc4'
    get 'slotbooker/fesemj'
    get 'slotbooker/fesemj1'
    get 'slotbooker/fesemj2'
    get 'slotbooker/fesemj3'
    get 'slotbooker/fesemj4'
    get 'slotbooker/icp'
    get 'slotbooker/icp1'
    get 'slotbooker/icp2'
    get 'slotbooker/icp3'
    get 'slotbooker/icp4'
    get 'slotbooker/laser'
    get 'slotbooker/laser1'
    get 'slotbooker/laser2'
    get 'slotbooker/laser3'
    get 'slotbooker/laser4'
    get 'slotbooker/lcms'
    get 'slotbooker/lcms1'
    get 'slotbooker/lcms2'
    get 'slotbooker/lcms3'
    get 'slotbooker/lcms4'
    get 'slotbooker/raman'
    get 'slotbooker/raman1'
    get 'slotbooker/raman2'
    get 'slotbooker/raman3'
    get 'slotbooker/raman4'
    get 'slotbooker/tga'
    get 'slotbooker/tga1'
    get 'slotbooker/tga2'
    get 'slotbooker/tga3'
    get 'slotbooker/tga4'
    get 'slotbooker/threednon'
    get 'slotbooker/threednon1'
    get 'slotbooker/threednon2'
    get 'slotbooker/threednon3'
    get 'slotbooker/threednon4'
    get 'slotbooker/uv'
    get 'slotbooker/uv1'
    get 'slotbooker/uv2'
    get 'slotbooker/uv3'
    get 'slotbooker/uv4'
    get 'slotbooker/spectro'
    get 'slotbooker/spectro1'
    get 'slotbooker/spectro2'
    get 'slotbooker/spectro3'
    get 'slotbooker/spectro4'
    get 'slotbooker/spark'
    get 'slotbooker/spark1'
    get 'slotbooker/spark2'
    get 'slotbooker/spark3'
    get 'slotbooker/spark4'
    get 'slotbooker/fiveaxis'
    get 'slotbooker/fiveaxis1'
    get 'slotbooker/fiveaxis2'
    get 'slotbooker/fiveaxis3'
    get 'slotbooker/fiveaxis4'
    get 'slotbooker/elctro'
    get 'slotbooker/elctro1'
    get 'slotbooker/elctro2'
    get 'slotbooker/elctro3'
    get 'slotbooker/elctro4'
    get 'slotbooker/nitrogen'
    get 'slotbooker/gassensing'
    get 'slotbooker/gassensing1'
    get 'slotbooker/gassensing2'
    get 'slotbooker/gassensing3'
    get 'slotbooker/gassensing4'
    get 'slotbooker/centrifuge'
    get 'slotbooker/centrifuge1'
    get 'slotbooker/centrifuge2'
    get 'slotbooker/centrifuge3'
    get 'slotbooker/centrifuge4'
    get 'slotbooker/probe'
    get 'slotbooker/probe1'
    get 'slotbooker/probe2'
    get 'slotbooker/probe3'
    get 'slotbooker/probe4'
    get 'slotbooker/glove'
    get 'slotbooker/glove1'
    get 'slotbooker/glove2'
    get 'slotbooker/glove3'
    get 'slotbooker/glove4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/milli'
    get 'slotbooker/integrated'
    get 'slotbooker/integrated1'
    get 'slotbooker/integrated2'
    get 'slotbooker/integrated3'
    get 'slotbooker/integrated4'
    get 'slotbooker/scratch'
    get 'slotbooker/scratch1'
    get 'slotbooker/scratch2'
    get 'slotbooker/scratch3'
    get 'slotbooker/scratch4'
    get 'slotbooker/threescanner'
    get 'slotbooker/threescanner1'
    get 'slotbooker/threescanner2'
    get 'slotbooker/threescanner3'
    get 'slotbooker/threescanner4'
    get 'slotbooker/impdeance'
    get 'slotbooker/impdeance1'

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # before_action :authenticate_admin!
  # load_and_authorize_resource class: Announcement
  # before_action :set_announcement, only: %i[ show edit update destroy ]


  def import
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    CsvImportService.new.call_announce(params[:file])

    redirect_to request.referer, notice: 'Import started...'
  end

  # GET /announcements or /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1 or /announcements/1.json
  def show
  end

  def authenticate_admin!
    unless current_user&.slotbooker == 'media'
      redirect_to home_index_path, alert: "You are not authorized to access this page."
    end
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements or /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully created." }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1 or /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully updated." }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1 or /announcements/1.json
  def destroy
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url, notice: "Announcement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:heading, :text, :created_on)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= stylesheet_link_tag "announcement"%>

<%= form_with(model: announcement) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
        <% announcement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="form">
    <div class="input-group mb-3 mt-3">
      <%= form.label :heading , class:'input-group-text' %>
      <%= form.text_area :heading, class:"form-control", placeholder:"Heading goes here...."  %>
    </div>
    <div class="input-group mb-3">
      <%= form.label :text , class:'input-group-text' %>
      <%= form.text_area :text, class:"form-control", placeholder:"Content goes here...." %>
    </div>
    <div class="input-group mb-3">
      <%= form.label :created_on , class:'input-group-text' %>
      <%= form.datetime_field :created_on, class:"form-select"%>
    </div>
    <div class="input-group mb-3">
      <%= form.submit "Create", class:"btn btn-primary", id:'sbt' %>
    </div>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "loginFeatures"%> <!--imported for the purpose of partial, has to be removed while code optimization -->
<%= stylesheet_link_tag "announcement"%> 

<%=render "partials/loginHeading"%>
<%=render "partials/formsBackbtn"%>

<h1 class="text-center font-unbounded" id="head-new">Editing Announcement</h1>
<div id="container-ann">
    <%= render 'form', announcement: @announcement %>
</div>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "announcement"%> <!-- this has to be removed during code optimization-->
<%= stylesheet_link_tag "loginFeatures"%> <!-- this has to be removed during code optimization-->
<%= stylesheet_link_tag "adminportal"%> <!-- this has to be removed during code optimization-->

<%=render "partials/announceNav"%>

<!-- <div id="container-ann">
 <table class="table">
  <thead id="thead">
    <tr class="table-head font-unbounded">
      <th scope="col">ID</th>
          <th scope="col">Heading</th>
          <th scope="col">Text</th>
          <th scope="col">Created on</th>
          <th scope="col">View</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <tbody>
      <% @announcements.each do |announcement| %>
        <tr>
          <td><%= announcement.id %></td>
          <td><%= announcement.heading %></td>
          <td><%= announcement.text %></td>
          <td><%= announcement.created_on %></td>
          <td><%= link_to 'Show', announcement, class:"btn btn-primary" %>

          </td>
          <td><%= link_to 'Edit', edit_announcement_path(announcement), class:"btn btn-success" %>


            </td>
          <td><%= link_to 'Delete', announcement, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </tbody>
</table>

  <%= link_to 'New Announcement', new_announcement_path, id:"new"%>


</div> -->


<div class="container1">
       <div class="announce-lists" id="item1">
           <h3 class="text-center fw-bold ">ANNOUNCEMENTS</h3>
           <div class="card" id="c1" >
               <div class="card-body">
                 <h5 class="card-title fw-bold">Announcement 1</h5>
                 <h6 class="card-subtitle mb-2 text-body-secondary">ID: 1425</h6>
                 <h6 class="card-subtitle mb-2 text-body-secondary">Created On: 12-05-2003</h6>
                 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.
                 lorem</p>
                 <a href="#1" id="view-btn" class="btn btn-danger">View</a>
               </div>
           </div>

           <div class="card" id="c2" >
               <div class="card-body">
                 <h5 class="card-title fw-bold">Announcement 1</h5>
                 <h6 class="card-subtitle mb-2 text-body-secondary">ID: 1425</h6>
                 <h6 class="card-subtitle mb-2 text-body-secondary">Created On: 12-05-2003</h6>
                 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                 <a href="#2" class="btn btn-danger">View</a>
               </div>
           </div>

           <div class="card" id="c3" >
               <div class="card-body">
                 <h5 class="card-title fw-bold">Announcement 1</h5>
                 <h6 class="card-subtitle mb-2 text-body-secondary">ID: 1425</h6>
                 <h6 class="card-subtitle mb-2 text-body-secondary">Created On: 12-05-2003</h6>
                 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                 <a href="#3" class="btn btn-danger">View</a>
               </div>
           </div>

           <div class="card" id="c4" >
               <div class="card-body">
                 <h5 class="card-title fw-bold">Announcement 1</h5>
                 <h6 class="card-subtitle mb-2 text-body-secondary">ID: 1425</h6>
                 <h6 class="card-subtitle mb-2 text-body-secondary">Created On: 12-05-2003</h6>
                 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                 <a href="#4" class="btn btn-danger">View</a>
               </div>
           </div>



       </div>
       <div class="announce-description" id="item2">
         <h3 class="text-center fw-bold">Announcement Description</h3>

         <div class="descriptions">
           <div class="card" id="1">
                <h5 class="card-header fw-bold">Announcement ID </h5>
                <div class="card-body">
                  <h5 class="card-title fw-bold">Announcement Heading </h5>
                  <p class="date">Created On:</p>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                  <!-- add correct view path -->
                  <a href="#" class="btn btn-primary">Edit</a>
                  <a href="#" class="btn btn-danger">Delete</a>

                </div>
          </div>

          <div class="card" id="2" >
               <h5 class="card-header fw-bold">Announcement ID 1</h5>
               <div class="card-body">
                 <h5 class="card-title fw-bold">Announcement Heading </h5>
                 <p class="date">Created On:</p>
                 <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                 <!-- add correct view path -->
                 <a href="#" class="btn btn-primary">Edit</a>
                 <a href="#" class="btn btn-danger">Delete</a>

               </div>
         </div>

         <div class="card" id="3">
              <h5 class="card-header fw-bold">Announcement ID:2 </h5>
              <div class="card-body">
                <h5 class="card-title fw-bold">Announcement Heading </h5>
                <p class="date">Created On:</p>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            lorem</p>
                <!-- add correct view path -->
                <a href="#" class="btn btn-primary">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>

              </div>
        </div>

        <div class="card" id="4">
             <h5 class="card-header fw-bold">Announcement ID:3 </h5>
             <div class="card-body">
               <h5 class="card-title fw-bold">Announcement Heading </h5>
               <p class="date">Created On:</p>
               <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
               <!-- add correct view path -->
               <a href="#" class="btn btn-primary">Edit</a>
               <a href="#" class="btn btn-danger">Delete</a>

             </div>
       </div>

       <div class="card" id="5">
            <h5 class="card-header fw-bold">Announcement ID 4</h5>
            <div class="card-body">
              <h5 class="card-title fw-bold">Announcement Heading </h5>
              <p class="date">Created On:</p>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <!-- add correct view path -->
              <a href="#" class="btn btn-primary">Edit</a>
              <a href="#" class="btn btn-danger">Delete</a>

            </div>
      </div>

      <div class="card" id="6">
           <h5 class="card-header fw-bold">Announcement ID 5</h5>
           <div class="card-body">
             <h5 class="card-title fw-bold">Announcement Heading </h5>
             <p class="date">Created On:</p>
             <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
             <!-- add correct view path -->
             <a href="#" class="btn btn-primary">Edit</a>
             <a href="#" class="btn btn-danger">Delete</a>

           </div>
     </div>
         </div>


       </div>
   </div>


   <!-- <script>
     function fetchContent(cardId) {
       var contentContainer = document.getElementById('contentContainer');
       contentContainer.innerHTML = ''; // Clear previous content

       // Fetch content based on cardId and update the content container
       if (cardId === 1) {
         contentContainer.innerHTML = '<h5>Content for Card 1</h5><p>Additional content for Card 1</p>';
       } else if (cardId === 2) {
         contentContainer.innerHTML = '<h5>Content for Card 2</h5><p>Additional content for Card 2</p>';
       }
     }
   </script> -->

app/views/announcements/new.html.erb
<%= stylesheet_link_tag "loginFeatures"%> <!--imported for the purpose of partial, has to be removed while code optimization -->
<%= stylesheet_link_tag "announcement"%> 

<%=render "partials/loginHeading"%>
<%=render "partials/formsBackbtn"%>

<h1 class="text-center font-unbounded" id="head-new">New Announcement</h1>
<div id="container-ann">
    
    <%= render 'form', announcement: @announcement %>
</div>
<%=render "partials/footer" %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "announcement"%>  <!-- this has to be removed during code optimization-->
<%= stylesheet_link_tag "loginFeatures"%> <!-- this has to be removed during code optimization-->
<%= stylesheet_link_tag "adminportal"%> <!-- this has to be removed during code optimization-->     
<%= stylesheet_link_tag "dashboard"%> <!-- this has to be removed during code optimization-->
<%=render "partials/announceNav"%> 

<p>
  
</p>
<h1 style="margin: 0 10px 0 10px">
  <strong><%=@announcement.heading %></strong>
</h1>
<p style="margin:10px; word-wrap:break-word"><%= @announcement.text %></p>

<p style="font-size:1.2em;margin:10px"><strong>Created on: </strong><%= @announcement.created_on %></p>


<div id="back-div">
  <div style="margin: 10px">
    <%= link_to "Back",  announcements_path, class:"btn btn-outline-warning profile-dropdown back-btn-forms" %>
  </div>
</div>