config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :announcements
  resources :equiplists
  get 'equips/index'
  get 'equips/show'
  get 'equips/new'
  get 'equips/create'
  get 'equips/destroy'
  post 'mainportal/adminModelEquip'
  post 'mainportal/adminModelUsers'
  root 'mainpage#landing'
  post 'mainportal/chairmanStats'
  post 'mainportal/chairmanStatsPayment'
  post 'mainportal/chairmanStatsSamples'
  post 'mainportal/adminAllSlots'




  resources :ft_nms
  resources :ansies
  resources :equipment_tables
  resources :lasers
  resources :three_d_scanners
  resources :impedance_analies
  resources :high_temp_vaccums
  resources :liquid_nitrogens
  resources :gas_sensings
  resources :ultra_centrifuges
  resources :probe_sonicators
  resources :glove_boxes
  resources :milli_qs
  resources :electro_chemicals
  resources :five_axis
  resources :micro_edms
  resources :spark_os
  resources :spectro_radio_meters
  resources :gaits
   resources :grindings
   resources :friction_stirs
   resources :frictions
   resources :multi_impact_testers
   resources :ball_mailings
   resources :glows
   resources :tribometers
   resources :low_fatigues
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   default_url_options :host => "localhost:3000"
    resources :zeta_potential_sizes
    resources :scratch_indentations
    resources :integrated_multi_role_testers
    resources :ion_chromotographies
    resources :advance_molecular_rheometers
    resources :icp_ms
    resources :ft_nmrs
    resources :atomic_force_microscopes
    resources :cell_imagings
    resources :uv_vis_nirs
    resources :hrlcms
    resources :bets
    resources :tga_fttrs
    resources :raman_microscopes
    resources :three_d_non_contacts
    resources :hr_fesem_js
    resources :hr_fesem_cs
    resources :xrds
    resources :faculties, controller: 'faculties'

    devise_for :users

    post 'home/developer'
    get 'mainportal/admindashboard'
    get 'mainportal/adminAllSlots'
    get 'mainportal/adminModelUsers'
    get 'mainportal/adminModelEquip'
    get 'mainportal/adminExpress'
    get 'mainportal/adminExpSlot'
    get 'mainportal/adminModelEquipWeeks'
    get 'mainportal/adminModelPayment'
    get 'mainportal/adminStats'
    get 'mainportal/chairmanDashboard'
    get 'mainportal/chairmanStats'
    get 'mainportal/chairmanEquip'
    get 'mainportal/chairmanPayment'
    get 'mainportal/chairmanUsers'
    get 'mainportal/chairmanStatsPayment'
    get 'mainportal/chairmanStatsSamples'
    get 'mainportal/exportfile'
    post 'download_liquid_nitrogen', to: 'mainportal#download_liquid_nitrogen', format: :csv
    get 'mainpage/landing'
    get 'home/index'
    get 'home/myslots'
    get 'home/anish'
    get 'know/xrd'
    get 'records/record'

    get 'home/mainPage'
    get 'mainpage/people'
    get 'mainpage/user_type'
    get 'mainpage/about_us'
    get 'mainpage/gallery'
    get 'mainpage/facility'
    get 'mainpage/announcement_admin'

    get 'mainpage/micromachining'
    get 'mainpage/xrd'
    get 'mainpage/axes_5'
    get 'mainpage/metal_3D'
    get 'mainpage/friction_stir'
    get 'mainpage/hvaf_hvof'
    get 'mainpage/hollow_fibre'

    get 'mainpage/fesem_c'
    get 'mainpage/hr_fesem_jeol'
    get 'mainpage/hr_lcms'
    get 'mainpage/xrd'
    get 'mainpage/three'
    get 'mainpage/bet'
    get 'mainpage/uv_vis'
    get 'mainpage/rheometer'
    get 'mainpage/raman'
    get 'mainpage/scanner_3d'
    get 'mainpage/tribometer'
    get 'mainpage/icp_ms'
    get 'mainpage/gas_sensing'
    get 'mainpage/atomic'
    get 'mainpage/tga'
    get 'mainpage/cell_imaging'
    get 'mainpage/ft_nmr'
    get 'mainpage/spark_oes'
    get 'mainpage/scratch_indentation'
    get 'mainpage/glow_discharge'
    get 'mainpage/multi_impact_test'
    get 'mainpage/integ_multirole'
    get 'mainpage/zeta'
    get 'mainpage/pressure_plate'
    get 'mainpage/impedance'
    get 'mainpage/laser'
    get 'mainpage/ion_chromatography'
    get 'mainpage/spectro'
    get 'mainpage/low_force_fatigue'
    get 'mainpage/chemisorption'
    get 'mainpage/instrumented_impact'
    get 'mainpage/gas_chromatography'
    get 'mainpage/proton_transfer'
    get 'mainpage/servo_hydraulic'
    get 'mainpage/gait'

    get 'mainpage/auto_multi_speci_polish'
    get 'mainpage/electro_chem'
    get 'mainpage/ultra_centrifuge'
    get 'mainpage/milli_q'
    get 'mainpage/glove_box'
    get 'mainpage/probe_sonicator'
    get 'mainpage/uv_ozone'
    get 'mainpage/high_temp_vac'
    get 'mainpage/liq_nitrogen'
    get 'mainpage/ball_milling'

    get 'mainpage/instrument_list'
    get 'mainpage/ft_nmr'
    get 'mainpage/xrd'
    get 'mainpage/hr_fesem_carl'
    get 'mainpage/friction_wear'
    get 'mainpage/multi_impact_test'
    get 'mainpage/multirole_mech'

    get 'feedbacks/index'


   get 'slot_mailer/xrd'
   get 'slot_mailer/advance_molecular_rheometer'
   get 'slot_mailer/bet'
   get 'slot_mailer/ball_mailing'
   get 'slot_mailer/cell_imaging'
   get 'slot_mailer/electro_chemical'
   get 'slot_mailer/five_axi'
   get 'slot_mailer/friction'
   get 'slot_mailer/ftnmr'
   get 'slot_mailer/gait'
   get 'slot_mailer/gas_sensing'
   get 'slot_mailer/glove_box'
   get 'slot_mailer/glow'
   get 'slot_mailer/grinding'
   get 'slot_mailer/high_temp_vaccum'
   get 'slot_mailer/hr_fesem_c'
   get 'slot_mailer/hr_fesem_j'
   get 'slot_mailer/icp_m'
   get 'slot_mailer/hr_lcm'
   get 'slot_mailer/impedence_analyzer'
   get 'slot_mailer/integrated_multi_role_tester'
   get 'slot_mailer/ion_chromatography'
   get 'slot_mailer/liquid_nitrogen'
   get 'slot_mailer/low_fatigue'
   get 'slot_mailer/laser'
   get 'slot_mailer/micro_edm'
   get 'slot_mailer/milli_q'
   get 'slot_mailer/multi_impact_tester'
   get 'slot_mailer/probe_sonicator'
   get 'slot_mailer/raman_microscope'
   get 'slot_mailer/scratch_indentation'
   get 'slot_mailer/spark_o'
   get 'slot_mailer/spectro_radio_meter'
   get 'slot_mailer/tga_fttr'
   get 'slot_mailer/three_d_non_contact'
   get 'slot_mailer/three_d_scanner'
   get 'slot_mailer/tribometer'
   get 'slot_mailer/ultra_centrifuge'
   get 'slot_mailer/uv_vis_nir'
   get 'slot_mailer/zeta_potential_size'




















    get 'home/developer'
    get 'slotbooker/xrd'
    get 'slotbooker/xrd1'
    post 'slotbooker/xrd1'
    patch 'slotbooker/xrd1'
    get 'slotbooker/xrd2'
    get 'slotbooker/xrd3'
    get 'slotbooker/xrd4'
    get 'slotbooker/atomic'
    get 'slotbooker/atomic1'
    get 'slotbooker/atomic2'
    get 'slotbooker/atomic3'
    get 'slotbooker/atomic4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/cell'
    get 'slotbooker/cell1'
    get 'slotbooker/cell2'
    get 'slotbooker/cell3'
    get 'slotbooker/cell4'
    get 'slotbooker/fesemc'
    get 'slotbooker/fesemc1'
    get 'slotbooker/fesemc2'
    get 'slotbooker/fesemc3'
    get 'slotbooker/fesemc4'
    get 'slotbooker/fesemj'
    get 'slotbooker/fesemj1'
    get 'slotbooker/fesemj2'
    get 'slotbooker/fesemj3'
    get 'slotbooker/fesemj4'
    get 'slotbooker/icp'
    get 'slotbooker/icp1'
    get 'slotbooker/icp2'
    get 'slotbooker/icp3'
    get 'slotbooker/icp4'
    get 'slotbooker/laser'
    get 'slotbooker/laser1'
    get 'slotbooker/laser2'
    get 'slotbooker/laser3'
    get 'slotbooker/laser4'
    get 'slotbooker/lcms'
    get 'slotbooker/lcms1'
    get 'slotbooker/lcms2'
    get 'slotbooker/lcms3'
    get 'slotbooker/lcms4'
    get 'slotbooker/raman'
    get 'slotbooker/raman1'
    get 'slotbooker/raman2'
    get 'slotbooker/raman3'
    get 'slotbooker/raman4'
    get 'slotbooker/tga'
    get 'slotbooker/tga1'
    get 'slotbooker/tga2'
    get 'slotbooker/tga3'
    get 'slotbooker/tga4'
    get 'slotbooker/threednon'
    get 'slotbooker/threednon1'
    get 'slotbooker/threednon2'
    get 'slotbooker/threednon3'
    get 'slotbooker/threednon4'
    get 'slotbooker/uv'
    get 'slotbooker/uv1'
    get 'slotbooker/uv2'
    get 'slotbooker/uv3'
    get 'slotbooker/uv4'
    get 'slotbooker/spectro'
    get 'slotbooker/spectro1'
    get 'slotbooker/spectro2'
    get 'slotbooker/spectro3'
    get 'slotbooker/spectro4'
    get 'slotbooker/spark'
    get 'slotbooker/spark1'
    get 'slotbooker/spark2'
    get 'slotbooker/spark3'
    get 'slotbooker/spark4'
    get 'slotbooker/fiveaxis'
    get 'slotbooker/fiveaxis1'
    get 'slotbooker/fiveaxis2'
    get 'slotbooker/fiveaxis3'
    get 'slotbooker/fiveaxis4'
    get 'slotbooker/elctro'
    get 'slotbooker/elctro1'
    get 'slotbooker/elctro2'
    get 'slotbooker/elctro3'
    get 'slotbooker/elctro4'
    get 'slotbooker/nitrogen'
    get 'slotbooker/gassensing'
    get 'slotbooker/gassensing1'
    get 'slotbooker/gassensing2'
    get 'slotbooker/gassensing3'
    get 'slotbooker/gassensing4'
    get 'slotbooker/centrifuge'
    get 'slotbooker/centrifuge1'
    get 'slotbooker/centrifuge2'
    get 'slotbooker/centrifuge3'
    get 'slotbooker/centrifuge4'
    get 'slotbooker/probe'
    get 'slotbooker/probe1'
    get 'slotbooker/probe2'
    get 'slotbooker/probe3'
    get 'slotbooker/probe4'
    get 'slotbooker/glove'
    get 'slotbooker/glove1'
    get 'slotbooker/glove2'
    get 'slotbooker/glove3'
    get 'slotbooker/glove4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/milli'
    get 'slotbooker/integrated'
    get 'slotbooker/integrated1'
    get 'slotbooker/integrated2'
    get 'slotbooker/integrated3'
    get 'slotbooker/integrated4'
    get 'slotbooker/scratch'
    get 'slotbooker/scratch1'
    get 'slotbooker/scratch2'
    get 'slotbooker/scratch3'
    get 'slotbooker/scratch4'
    get 'slotbooker/threescanner'
    get 'slotbooker/threescanner1'
    get 'slotbooker/threescanner2'
    get 'slotbooker/threescanner3'
    get 'slotbooker/threescanner4'
    get 'slotbooker/impdeance'
    get 'slotbooker/impdeance1'

app/models/gait.rb
class Gait < ApplicationRecord
  has_many_attached :references
  has_many_attached :ethicals
  has_many_attached :prescrptions
  has_many_attached :clinicals
  belongs_to :user
  has_one :equipment_table, :dependent => :destroy
  accepts_nested_attributes_for :equipment_table
  serialize :output_format
  after_create :update_equipment
  def update_equipment
    equipment_table = self.equipment_table # Find the specific AnotherTable record
    equipment_table.update(app_no: "CRF/GT/#{self.id}") 
  end
end

app/controllers/gaits_controller.rb
class GaitsController < ApplicationController
  before_action :set_gait, only: %i[ show edit update destroy ]

  # GET /gaits or /gaits.json
  def index
    @gaits = Gait.all
  end

  # GET /gaits/1 or /gaits/1.json
  def show
  end

  # GET /gaits/new
  def new
    @gait = Gait.new
    @user=User.find(params[:id])
    @gait.build_equipment_table

  end

  # GET /gaits/1/edit
  def edit
  end

  # POST /gaits or /gaits.json
  def create
   @gait = Gait.new(gait_params)
    @gait.user=current_user
    @gait.status="pending"
    @gait.build_equipment_table
    if(@gait.entry_type== "manual")
      @gait.equipment_table.dummy = "proforma_confirmed"
      @gait.equipment_table.equipname = @gait.dummy1
      @gait.equipment_table.pay = @gait.amount
      @gait.equipment_table.username = @gait.dummy2
      @gait.equipment_table.debit_head = @gait.debit
      @gait.equipment_table.role = @gait.dummy3
      @gait.dummy2 = nil
      @gait.dummy3 = nil
    else
    @gait.equipment_table.dummy = "alloted"
    @gait.equipment_table.username = @gait.user.name
    @gait.equipment_table.equipname = "GAIT Analysis"
    @gait.equipment_table.debit_head = @gait.debit
    @gait.equipment_table.role = @gait.user.role
    @gait.equipment_table.email = @gait.user.email
    @gait.equipment_table.dept = @gait.user.department
    @gait.equipment_table.profesion = @gait.user.profession
    @gait.equipment_table.orgname = @gait.user.orgname
  end


    respond_to do |format|
      if @gait.save
        if @gait.user.role=='student'||@gait.user.role=='faculty'
          GaitMailer.with(id:@gait.id, userid:current_user.id).InternalMail.deliver_later
        else
          GaitMailer.with(id:@gait.id, userid:current_user.id).ExternalMail.deliver_later
        end
        if @gait.entry_type=="manual"
            format.html { redirect_to payment_paymentM_path, notice: "gait was successfully created." }
            format.json { render :show, status: :created, location: @gait }
        else
        format.html { redirect_to home_index_path, notice: "Gait was successfully created." }
        format.json { render :show, status: :created, location: @gait }
      end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gaits/1 or /gaits/1.json
  def update
      @gait.status="alloted"
      @gait.build_equipment_table
    respond_to do |format|
      if @gait.update(gait_params)
        if @gait.status!= 'completed'
          GaitAllotedMailer.with(id:@gait.id, userid:current_user.id).Mail.deliver_later
        end
        format.html { redirect_to slotbooker_gait_path(@gait), notice: "Gait was successfully updated." }
        format.json { render :show, status: :ok, location: @gait }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gait.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gaits/1 or /gaits/1.json
  def destroy
    @gait.destroy

    respond_to do |format|
      format.html { redirect_to gaits_url, notice: "Gait was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gait
      @gait = Gait.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gait_params
      params.require(:gait).permit(:subject, :measurement, :trials, :force_plate, :clinical_trial, :physician, :more, :status, :slotdate, :slottime, :debit,:user_id,:entry_type,:amount,:dummy1,:dummy2,:dummy3, equipment_table_attributes: [:username, :app_no, :debit_head, :dummy, :pay, :dept, :equipname, :email,:role, :profesion, :orgaddress, :orgname] ,ethicals: [], prescrptions: [],clinicals: [],output_format: [], references: [])
    end
end

app/helpers/gaits_helper.rb
module GaitsHelper
end

app/views/gaits/_form.html.erb
<%= stylesheet_link_tag "loginFeatures"%>
<%= stylesheet_link_tag "equipmentQuestion"%>




<%=render "partials/loginHeading"%>
<%=render "partials/formsBackbtn"%>



<div class="container">
    <div id="equipment-name">
      <h1>GAIT Analysis</h1>
    </div>
    <div class='hero'>
      <%= form_with(model: gait) do |form| %>
        <% if gait.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(gait.errors.count, "error") %> prohibited this gait from being saved:</h2>

            <ul>
              <% gait.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
    <h6 class="text-danger">(*Ethical Clearance mandatory to upload)</h6>
    <div class="input-group mb-3">
      <%= form.label :trials,"No of Trails", class:"input-group-text", for:"trail_no"%>
      <%= form.select(:trials, [1, 2,3,4,5], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "trail_no",:required => true}) %>
    </div>
    <div class="input-group mb-3">
      <%= form.label :subject,"Subjects are:", class:"input-group-text", for:"subject"%>
      <%= form.select(:subject, ["Healthy","Patient"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id =>"subject",:required => true}) %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :measurement,"Type of Measurement", class:"input-group-text", for:"measure_type"%>
      <%= form.select(:measurement, ["Upper Body","Lower Body","Full Body"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id =>"measure_type",:required => true}) %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :trials,"No of Trails", class:"input-group-text", for:"trail_no"%>
      <%= form.select(:trials, [1, 2,3,4,5], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "trail_no",:required => true}) %>
    </div>

    <div class="input-group mb-3">
        <div class="fw-bold">
            Whether Force Plate included:-
        </div>



        <div class="input-group mb-3">
            <div class="form-check form-check-inline">
                <%= form.radio_button :force_plate, "Yes", class:"form-check-input", type:"radio", id:"force_plate_yes",:checked => true %>
                <%= form.label :force_plate, "Yes", class:"form-check-label", for:"force_plate_yes"%>
            </div>
            <div class="form-check form-check-inline">
                  <%= form.radio_button :force_plate, 'No', class:"form-check-input", type:"radio", id:"force_plate_no"  %>
                  <%= form.label :force_plate, "No", class:"form-check-label", for:"force_plate_no"%>
            </div>
        </div>
    </div>

    <div class="input-group mb-3">
        <h6 class="fw-bold">Final output format required</h6>
    </div>
    <% options = ['.mat', '.tsv','.c3d','.doc'] %>
    <% options.each do |option| %>
      <%= check_box_tag 'gait[output_format][]', option, @gait.output_format.include?(option),checked: option=='.tsv' %>
      <%= label_tag "gait_output_format_#{option}", option %><br>
    <% end %>

    <div class="input-group mb-3">
      <%= form.label :clinical_trial,"Clinical Trail Insurance Taken", class:"input-group-text", for:"clinical_trail"%>
      <%= form.select(:clinical_trial, ["Yes","No"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id =>"clinical_trail",:required => true}) %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :physician,"Prescribed by any Physician", class:"input-group-text", for:"physician"%>
      <%= form.select(:physician, ["Yes","No"], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id =>"physician",:required => true}) %>
    </div>

    <div class="input-group mb-3">
        <h6 class="fw-bold text-danger">Attach Reports.<span class="text-success"> [max. size 5 MB, .pdf only] </span></h6>
    </div>

    <div class="input-group mb-3" id="ethical-clearnace-input">
      <%= form.label :ethicals ,"Attach Ethical Clearance*" ,for:"ethical-clearance", class:"input-group-text text-info"%>
      <%= form.file_field :ethicals,class:"form-control ",  id:"ethical-clearance",multiple:true  %>
    </div>

    <div class="input-group mb-3 vis" id="phy-pres-input">
      <%= form.label :prescrptions ,"Attach Physician Prescription" ,for:"attach_phy_prescp", class:"input-group-text text-info"%>
      <%= form.file_field :prescrptions,class:"form-control ",  id:"attach_phy_prescp",multiple:true  %>
    </div>

    <div class="input-group mb-3 vis" id="insurance-input">
      <%= form.label :clinicals ,"Attach Clinical Trail Insurance" ,for:"insurance", class:"input-group-text text-info"%>
      <%= form.file_field :clinicals,class:"form-control ",  id:"insurance",multiple:true  %>
    </div>

    <div class="input-group mb-3" id="collegeid-input">
      <%= form.label :references ,"Attach Reference Paper(optional)" ,for:"upload-file", class:"input-group-text "%>
      <%= form.file_field :references,class:"form-control ",  id:"upload-file",multiple:true  %>
    </div>


    <div class="input-group mb-3">
      <%= form.label :debit,"Choose Debit Head ", class:"input-group-text", for:"debit-head-select" %>
      <%= form.select(:debit, ['Department Operating Cost', 'Student Contingency','CPDA Fund','Project Fund'], {:include_blank => 'Choose...'},{ :class => 'form-select' ,:id => "debit-head-select",:required => true}) %>
  </div>

  <div id="instruct">
      <p class="text-danger">*Please select your Debit head as per your mode of Payment</p>
  </div>




    <div class="input-group mb-3">
      <%= form.text_field :more, class:"form-control", id:"brief_descrp", placeholder:"Brief Experiment Description (max. 200 chars)"%>
    </div>

    <div class="actions">
        <%= form.submit "Submit", class:"btn btn-primary", id:"sbt" %>
    </div>

  </div>
</div>


<%=render "partials/footer" %>

<script>
    let subject = document.getElementById('subject')
    let physician = document.getElementById('physician')
    let phy_pres_input = document.getElementById('phy-pres-input')
    let ethical_clearnace_input = document.getElementById('ethical-clearnace-input')
    let clinical_trail = document.getElementById('clinical_trail')
    let insuarance = document.getElementById('insurance-input')

    physician.addEventListener('change', ()=> {
        phy_pres_input.classList.add('vis');

        if(physician.value == "Yes") {
            phy_pres_input.classList.toggle('vis')
        }
    })
    clinical_trail.addEventListener('change', ()=> {
        insuarance.classList.add('vis');

        if(clinical_trail.value == "Yes") {
            insuarance.classList.toggle('vis')
        }
    })

</script>

<% end %>

app/views/gaits/edit.html.erb
<h1>Editing Gait</h1>

<%= render 'form', gait: @gait %>

<%= link_to 'Show', @gait %> |
<%= link_to 'Back', gaits_path %>

app/views/gaits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gaits</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Measurement</th>
      <th>Trials</th>
      <th>Force plate</th>
      <th>Clinical trial</th>
      <th>Physician</th>
      <th>More</th>
      <th>Status</th>
      <th>Slotdate</th>
      <th>Slottime</th>
      <th>Debit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gaits.each do |gait| %>
      <tr>
        <td><%= gait.subject %></td>
        <td><%= gait.measurement %></td>
        <td><%= gait.trials %></td>
        <td><%= gait.force_plate %></td>
        <td><%= gait.clinical_trial %></td>
        <td><%= gait.physician %></td>
        <td><%= gait.more %></td>
        <td><%= gait.status %></td>
        <td><%= gait.slotdate %></td>
        <td><%= gait.slottime %></td>
        <td><%= gait.debit %></td>
        <td><%= link_to 'Show', gait %></td>
        <td><%= link_to 'Edit', edit_gait_path(gait) %></td>
        <td><%= link_to 'Destroy', gait, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gait', new_gait_path %>

app/views/gaits/new.html.erb
<%= render 'form', gait: @gait %>

app/views/gaits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @gait.subject %>
</p>

<p>
  <strong>Measurement:</strong>
  <%= @gait.measurement %>
</p>

<p>
  <strong>Trials:</strong>
  <%= @gait.trials %>
</p>

<p>
  <strong>Force plate:</strong>
  <%= @gait.force_plate %>
</p>

<p>
  <strong>Clinical trial:</strong>
  <%= @gait.clinical_trial %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @gait.physician %>
</p>

<p>
  <strong>More:</strong>
  <%= @gait.more %>
</p>

<p>
  <strong>Status:</strong>
  <%= @gait.status %>
</p>

<p>
  <strong>Slotdate:</strong>
  <%= @gait.slotdate %>
</p>

<p>
  <strong>Slottime:</strong>
  <%= @gait.slottime %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @gait.debit %>
</p>

<%= link_to 'Edit', edit_gait_path(@gait) %> |
<%= link_to 'Back', gaits_path %>