config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :announcements
  resources :equiplists
  get 'equips/index'
  get 'equips/show'
  get 'equips/new'
  get 'equips/create'
  get 'equips/destroy'
  post 'mainportal/adminModelEquip'
  post 'mainportal/adminModelUsers'
  root 'mainpage#landing'
  post 'mainportal/chairmanStats'
  post 'mainportal/chairmanStatsPayment'
  post 'mainportal/chairmanStatsSamples'
  post 'mainportal/adminAllSlots'




  resources :ft_nms
  resources :ansies
  resources :equipment_tables
  resources :lasers
  resources :three_d_scanners
  resources :impedance_analies
  resources :high_temp_vaccums
  resources :liquid_nitrogens
  resources :gas_sensings
  resources :ultra_centrifuges
  resources :probe_sonicators
  resources :glove_boxes
  resources :milli_qs
  resources :electro_chemicals
  resources :five_axis
  resources :micro_edms
  resources :spark_os
  resources :spectro_radio_meters
  resources :gaits
   resources :grindings
   resources :friction_stirs
   resources :frictions
   resources :multi_impact_testers
   resources :ball_mailings
   resources :glows
   resources :tribometers
   resources :low_fatigues
 mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   default_url_options :host => "localhost:3000"
    resources :zeta_potential_sizes
    resources :scratch_indentations
    resources :integrated_multi_role_testers
    resources :ion_chromotographies
    resources :advance_molecular_rheometers
    resources :icp_ms
    resources :ft_nmrs
    resources :atomic_force_microscopes
    resources :cell_imagings
    resources :uv_vis_nirs
    resources :hrlcms
    resources :bets
    resources :tga_fttrs
    resources :raman_microscopes
    resources :three_d_non_contacts
    resources :hr_fesem_js
    resources :hr_fesem_cs
    resources :xrds
    resources :faculties, controller: 'faculties'

    devise_for :users

    post 'home/developer'
    get 'mainportal/admindashboard'
    get 'mainportal/adminAllSlots'
    get 'mainportal/adminModelUsers'
    get 'mainportal/adminModelEquip'
    get 'mainportal/adminExpress'
    get 'mainportal/adminExpSlot'
    get 'mainportal/adminModelEquipWeeks'
    get 'mainportal/adminModelPayment'
    get 'mainportal/adminStats'
    get 'mainportal/chairmanDashboard'
    get 'mainportal/chairmanStats'
    get 'mainportal/chairmanEquip'
    get 'mainportal/chairmanPayment'
    get 'mainportal/chairmanUsers'
    get 'mainportal/chairmanStatsPayment'
    get 'mainportal/chairmanStatsSamples'
    get 'mainportal/exportfile'
    post 'download_liquid_nitrogen', to: 'mainportal#download_liquid_nitrogen', format: :csv
    get 'mainpage/landing'
    get 'home/index'
    get 'home/myslots'
    get 'home/anish'
    get 'know/xrd'
    get 'records/record'

    get 'home/mainPage'
    get 'mainpage/people'
    get 'mainpage/user_type'
    get 'mainpage/about_us'
    get 'mainpage/gallery'
    get 'mainpage/facility'
    get 'mainpage/announcement_admin'

    get 'mainpage/micromachining'
    get 'mainpage/xrd'
    get 'mainpage/axes_5'
    get 'mainpage/metal_3D'
    get 'mainpage/friction_stir'
    get 'mainpage/hvaf_hvof'
    get 'mainpage/hollow_fibre'

    get 'mainpage/fesem_c'
    get 'mainpage/hr_fesem_jeol'
    get 'mainpage/hr_lcms'
    get 'mainpage/xrd'
    get 'mainpage/three'
    get 'mainpage/bet'
    get 'mainpage/uv_vis'
    get 'mainpage/rheometer'
    get 'mainpage/raman'
    get 'mainpage/scanner_3d'
    get 'mainpage/tribometer'
    get 'mainpage/icp_ms'
    get 'mainpage/gas_sensing'
    get 'mainpage/atomic'
    get 'mainpage/tga'
    get 'mainpage/cell_imaging'
    get 'mainpage/ft_nmr'
    get 'mainpage/spark_oes'
    get 'mainpage/scratch_indentation'
    get 'mainpage/glow_discharge'
    get 'mainpage/multi_impact_test'
    get 'mainpage/integ_multirole'
    get 'mainpage/zeta'
    get 'mainpage/pressure_plate'
    get 'mainpage/impedance'
    get 'mainpage/laser'
    get 'mainpage/ion_chromatography'
    get 'mainpage/spectro'
    get 'mainpage/low_force_fatigue'
    get 'mainpage/chemisorption'
    get 'mainpage/instrumented_impact'
    get 'mainpage/gas_chromatography'
    get 'mainpage/proton_transfer'
    get 'mainpage/servo_hydraulic'
    get 'mainpage/gait'

    get 'mainpage/auto_multi_speci_polish'
    get 'mainpage/electro_chem'
    get 'mainpage/ultra_centrifuge'
    get 'mainpage/milli_q'
    get 'mainpage/glove_box'
    get 'mainpage/probe_sonicator'
    get 'mainpage/uv_ozone'
    get 'mainpage/high_temp_vac'
    get 'mainpage/liq_nitrogen'
    get 'mainpage/ball_milling'

    get 'mainpage/instrument_list'
    get 'mainpage/ft_nmr'
    get 'mainpage/xrd'
    get 'mainpage/hr_fesem_carl'
    get 'mainpage/friction_wear'
    get 'mainpage/multi_impact_test'
    get 'mainpage/multirole_mech'

    get 'feedbacks/index'


   get 'slot_mailer/xrd'
   get 'slot_mailer/advance_molecular_rheometer'
   get 'slot_mailer/bet'
   get 'slot_mailer/ball_mailing'
   get 'slot_mailer/cell_imaging'
   get 'slot_mailer/electro_chemical'
   get 'slot_mailer/five_axi'
   get 'slot_mailer/friction'
   get 'slot_mailer/ftnmr'
   get 'slot_mailer/gait'
   get 'slot_mailer/gas_sensing'
   get 'slot_mailer/glove_box'
   get 'slot_mailer/glow'
   get 'slot_mailer/grinding'
   get 'slot_mailer/high_temp_vaccum'
   get 'slot_mailer/hr_fesem_c'
   get 'slot_mailer/hr_fesem_j'
   get 'slot_mailer/icp_m'
   get 'slot_mailer/hr_lcm'
   get 'slot_mailer/impedence_analyzer'
   get 'slot_mailer/integrated_multi_role_tester'
   get 'slot_mailer/ion_chromatography'
   get 'slot_mailer/liquid_nitrogen'
   get 'slot_mailer/low_fatigue'
   get 'slot_mailer/laser'
   get 'slot_mailer/micro_edm'
   get 'slot_mailer/milli_q'
   get 'slot_mailer/multi_impact_tester'
   get 'slot_mailer/probe_sonicator'
   get 'slot_mailer/raman_microscope'
   get 'slot_mailer/scratch_indentation'
   get 'slot_mailer/spark_o'
   get 'slot_mailer/spectro_radio_meter'
   get 'slot_mailer/tga_fttr'
   get 'slot_mailer/three_d_non_contact'
   get 'slot_mailer/three_d_scanner'
   get 'slot_mailer/tribometer'
   get 'slot_mailer/ultra_centrifuge'
   get 'slot_mailer/uv_vis_nir'
   get 'slot_mailer/zeta_potential_size'




















    get 'home/developer'
    get 'slotbooker/xrd'
    get 'slotbooker/xrd1'
    post 'slotbooker/xrd1'
    patch 'slotbooker/xrd1'
    get 'slotbooker/xrd2'
    get 'slotbooker/xrd3'
    get 'slotbooker/xrd4'
    get 'slotbooker/atomic'
    get 'slotbooker/atomic1'
    get 'slotbooker/atomic2'
    get 'slotbooker/atomic3'
    get 'slotbooker/atomic4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/cell'
    get 'slotbooker/cell1'
    get 'slotbooker/cell2'
    get 'slotbooker/cell3'
    get 'slotbooker/cell4'
    get 'slotbooker/fesemc'
    get 'slotbooker/fesemc1'
    get 'slotbooker/fesemc2'
    get 'slotbooker/fesemc3'
    get 'slotbooker/fesemc4'
    get 'slotbooker/fesemj'
    get 'slotbooker/fesemj1'
    get 'slotbooker/fesemj2'
    get 'slotbooker/fesemj3'
    get 'slotbooker/fesemj4'
    get 'slotbooker/icp'
    get 'slotbooker/icp1'
    get 'slotbooker/icp2'
    get 'slotbooker/icp3'
    get 'slotbooker/icp4'
    get 'slotbooker/laser'
    get 'slotbooker/laser1'
    get 'slotbooker/laser2'
    get 'slotbooker/laser3'
    get 'slotbooker/laser4'
    get 'slotbooker/lcms'
    get 'slotbooker/lcms1'
    get 'slotbooker/lcms2'
    get 'slotbooker/lcms3'
    get 'slotbooker/lcms4'
    get 'slotbooker/raman'
    get 'slotbooker/raman1'
    get 'slotbooker/raman2'
    get 'slotbooker/raman3'
    get 'slotbooker/raman4'
    get 'slotbooker/tga'
    get 'slotbooker/tga1'
    get 'slotbooker/tga2'
    get 'slotbooker/tga3'
    get 'slotbooker/tga4'
    get 'slotbooker/threednon'
    get 'slotbooker/threednon1'
    get 'slotbooker/threednon2'
    get 'slotbooker/threednon3'
    get 'slotbooker/threednon4'
    get 'slotbooker/uv'
    get 'slotbooker/uv1'
    get 'slotbooker/uv2'
    get 'slotbooker/uv3'
    get 'slotbooker/uv4'
    get 'slotbooker/spectro'
    get 'slotbooker/spectro1'
    get 'slotbooker/spectro2'
    get 'slotbooker/spectro3'
    get 'slotbooker/spectro4'
    get 'slotbooker/spark'
    get 'slotbooker/spark1'
    get 'slotbooker/spark2'
    get 'slotbooker/spark3'
    get 'slotbooker/spark4'
    get 'slotbooker/fiveaxis'
    get 'slotbooker/fiveaxis1'
    get 'slotbooker/fiveaxis2'
    get 'slotbooker/fiveaxis3'
    get 'slotbooker/fiveaxis4'
    get 'slotbooker/elctro'
    get 'slotbooker/elctro1'
    get 'slotbooker/elctro2'
    get 'slotbooker/elctro3'
    get 'slotbooker/elctro4'
    get 'slotbooker/nitrogen'
    get 'slotbooker/gassensing'
    get 'slotbooker/gassensing1'
    get 'slotbooker/gassensing2'
    get 'slotbooker/gassensing3'
    get 'slotbooker/gassensing4'
    get 'slotbooker/centrifuge'
    get 'slotbooker/centrifuge1'
    get 'slotbooker/centrifuge2'
    get 'slotbooker/centrifuge3'
    get 'slotbooker/centrifuge4'
    get 'slotbooker/probe'
    get 'slotbooker/probe1'
    get 'slotbooker/probe2'
    get 'slotbooker/probe3'
    get 'slotbooker/probe4'
    get 'slotbooker/glove'
    get 'slotbooker/glove1'
    get 'slotbooker/glove2'
    get 'slotbooker/glove3'
    get 'slotbooker/glove4'
    get 'slotbooker/bet'
    get 'slotbooker/bet1'
    get 'slotbooker/bet2'
    get 'slotbooker/bet3'
    get 'slotbooker/bet4'
    get 'slotbooker/milli'
    get 'slotbooker/integrated'
    get 'slotbooker/integrated1'
    get 'slotbooker/integrated2'
    get 'slotbooker/integrated3'
    get 'slotbooker/integrated4'
    get 'slotbooker/scratch'
    get 'slotbooker/scratch1'
    get 'slotbooker/scratch2'
    get 'slotbooker/scratch3'
    get 'slotbooker/scratch4'
    get 'slotbooker/threescanner'
    get 'slotbooker/threescanner1'
    get 'slotbooker/threescanner2'
    get 'slotbooker/threescanner3'
    get 'slotbooker/threescanner4'
    get 'slotbooker/impdeance'
    get 'slotbooker/impdeance1'

app/helpers/equipment_tables_helper.rb
module EquipmentTablesHelper
end

app/views/equipment_tables/_form.html.erb
<%= form_with(model: equipment_table) do |form| %>
  <% if equipment_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment_table.errors.count, "error") %> prohibited this equipment_table from being saved:</h2>

      <ul>
        <% equipment_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :equipname %>
    <%= form.text_field :equipname %>
  </div>

  <div class="field">
    <%= form.label :app_no %>
    <%= form.text_field :app_no %>
  </div>

  <div class="field">
    <%= form.label :pay %>
    <%= form.text_field :pay %>
  </div>

  <div class="field">
    <%= form.label :debit_head %>
    <%= form.text_field :debit_head %>
  </div>

  <div class="field">
    <%= form.label :slotd %>
    <%= form.date_select :slotd %>
  </div>

  <div class="field">
    <%= form.label :slott %>
    <%= form.time_select :slott %>
  </div>

  <div class="field">
    <%= form.label :dummy %>
    <%= form.text_field :dummy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/equipment_tables/edit.html.erb
<h1>Editing Equipment Table</h1>

<%= render 'form', equipment_table: @equipment_table %>

<%= link_to 'Show', @equipment_table %> |
<%= link_to 'Back', equipment_tables_path %>

app/views/equipment_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipment Tables</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Equipname</th>
      <th>App no</th>
      <th>Pay</th>
      <th>Debit head</th>
      <th>Slotd</th>
      <th>Slott</th>
      <th>Dummy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment_tables.each do |equipment_table| %>
      <tr>
        <td><%= equipment_table.username %></td>
        <td><%= equipment_table.equipname %></td>
        <td><%= equipment_table.app_no %></td>
        <td><%= equipment_table.pay %></td>
        <td><%= equipment_table.debit_head %></td>
        <td><%= equipment_table.slotd %></td>
        <td><%= equipment_table.slott %></td>
        <td><%= equipment_table.dummy %></td>
        <td><%= link_to 'Show', equipment_table %></td>
        <td><%= link_to 'Edit', edit_equipment_table_path(equipment_table) %></td>
        <td><%= link_to 'Destroy', equipment_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment Table', new_equipment_table_path %>

app/views/equipment_tables/new.html.erb
<h1>New Equipment Table</h1>

<%= render 'form', equipment_table: @equipment_table %>

<%= link_to 'Back', equipment_tables_path %>

app/views/equipment_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @equipment_table.username %>
</p>

<p>
  <strong>Equipname:</strong>
  <%= @equipment_table.equipname %>
</p>

<p>
  <strong>App no:</strong>
  <%= @equipment_table.app_no %>
</p>

<p>
  <strong>Pay:</strong>
  <%= @equipment_table.pay %>
</p>

<p>
  <strong>Debit head:</strong>
  <%= @equipment_table.debit_head %>
</p>

<p>
  <strong>Slotd:</strong>
  <%= @equipment_table.slotd %>
</p>

<p>
  <strong>Slott:</strong>
  <%= @equipment_table.slott %>
</p>

<p>
  <strong>Dummy:</strong>
  <%= @equipment_table.dummy %>
</p>

<%= link_to 'Edit', edit_equipment_table_path(@equipment_table) %> |
<%= link_to 'Back', equipment_tables_path %>